### ISSUE TITLE
Carbon product hostname should not point to marathonlb

### ISSUE THREAD

**Issue by udaraliyanage** [wso2-attic/puppet-modules#73] opened 2016-07-04 05:34 UTC
Hostnames of all the products are pointed to marathon-lb hostname. 
IMO hostname of a product should points to product's hostname regardless of the fact that product is load balanced via marathon LB. It is the responsibility of the deployment to map those product hostnames to ip of marathonlb or any other external such as ELB [1]

wso2::apim_keymanager:
  host: marathon-lb.marathon.mesos

[1] https://mesosphere.com/blog/2016/04/06/lets-encrypt-dcos/

**Comment by imesh** [comment] 2016-07-04 11:22
Yes definitely Udara! Will check the reason for doing that and change it accordingly!  Thanks!

**Comment by imesh** [comment] 2016-07-22 12:56
We have done this as a workaround for a limitation in Mesos DCOS. The problem is as follows:
- Cluster hostnames are used by WSO2 products for load balancing, providing absolute URLs in HTML body (in UIs), making internal calls to its dependencies and itself.
- Mesos DCOS currently does not have a service concept similar to Kubernetes services for resolving hostnames to its cluster and providing a fixed set of ports.
- Mesos DNS points to Mesos slaves and they can only be used with host ports. For scalability reasons host ports should be dynamic.
- Therefore Mesos DNS with Marathon application names cannot be used for cluster hostnames.
- We have used marathon load balancer hostname as the cluster hostname of all products for this reason as it provides fixed ports. This has been done to make the out of the box scenario working.
- In a real deployment this can be fixed by using a DNS server and adding DNS entries for each cluster hostname.

**Closed** 2021-10-05 03:51 UTC
Labels: bug, wontfix
